apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "muffin-currency.fullname" . }}
    labels:
        app: {{ include "muffin-currency.name" . }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ include "muffin-currency.name" . }}
    template:
        metadata:
            labels:
                app: {{ include "muffin-currency.name" . }}
        spec:
            containers:
                - name: {{ include "muffin-currency.name" . }}
                  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                  imagePullPolicy: {{ .Values.image.pullPolicy }}
                  ports:
                      - containerPort: {{ .Values.containerPort }}
                  livenessProbe:
                      httpGet:
                          path: {{ .Values.probes.liveness.path }}
                          port: {{ .Values.containerPort }}
                      initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
                      periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
                  readinessProbe:
                      httpGet:
                          path: {{ .Values.probes.readiness.path }}
                          port: {{ .Values.containerPort }}
                      initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
                      periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
