apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-currency.fullname" . }}
  labels:
    app: {{ include "muffin-currency.name" . }}
spec:
    selector:
        app: {{ include "muffin-currency.name" . }}
    ports:
        - name: http
          protocol: TCP
          port: {{ .Values.service.port }}
          targetPort: {{ .Values.service.targetPort }}
    type: {{ .Values.service.type }}
