apiVersion: v1
kind: Service
metadata:
    name: {{ include "muffin-currency.fullname" . }}
spec:
    selector:
        app: {{ include "muffin-currency.name" . }}
    ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
          targetPort: {{ .Values.service.targetPort }}
    type: {{ .Values.service.type }}
