apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muffin-wallet.envConfigMapName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
data:
  SERVER_PORT: "{{ .Values.containerPort }}"
  JDK_JAVA_OPTIONS: -Dspring.config.additional-location=/app/config/application.yaml
  ZIPKIN_ENDPOINT: http://tempo.monitoring.svc.cluster.local:9411/api/v2/spans