apiVersion: v1
kind: Secret
metadata:
  name: {{ include "muffin-wallet.secretName" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.SPRING_DATASOURCE_PASSWORD | b64enc }}
